# Generated by Django 5.1 on 2024-09-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_local_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='adress',
            new_name='address',
        ),
    ]
