# Generated by Django 5.1 on 2024-09-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_adress_bodega_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='nombre',
            new_name='name',
        ),
    ]
